Fix calendar and input-otp errors
Fixes the following errors:
- src/components/ui/calendar.tsx(56,9): error TS2353: Object literal may only specify known properties, and 'IconLeft' does not exist in type 'Partial<CustomComponents>'.
- src/components/ui/input-otp.tsx(2,43): error TS2307: Cannot find module 'input-otp' or its corresponding type declarations.
- src/components/ui/input-otp.tsx(36,60): error TS2339: Property 'slots' does not exist on type 'unknown'.